// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A testimonial highlighter AI agent.
 *
 * - highlightTestimonials - A function that handles the testimonial highlighting process.
 * - HighlightTestimonialsInput - The input type for the highlightTestimonials function.
 * - HighlightTestimonialsOutput - The return type for the highlightTestimonials function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HighlightTestimonialsInputSchema = z.object({
  testimonials: z.array(z.string()).describe('An array of customer testimonials.'),
});
export type HighlightTestimonialsInput = z.infer<typeof HighlightTestimonialsInputSchema>;

const HighlightTestimonialsOutputSchema = z.object({
  highlightedTestimonials: z.array(z.string()).describe('An array of highlighted customer testimonials.'),
});
export type HighlightTestimonialsOutput = z.infer<typeof HighlightTestimonialsOutputSchema>;

export async function highlightTestimonials(input: HighlightTestimonialsInput): Promise<HighlightTestimonialsOutput> {
  return highlightTestimonialsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'highlightTestimonialsPrompt',
  input: {schema: HighlightTestimonialsInputSchema},
  output: {schema: HighlightTestimonialsOutputSchema},
  prompt: `You are an expert marketing copywriter specializing in highlighting the most compelling parts of customer testimonials.

  Given the following testimonials, identify and highlight the key phrases or sentences that showcase the product's benefits and value.
  Return an array of the highlighted testimonials.

  Testimonials:
  {{#each testimonials}}
  - {{{this}}}
  {{/each}}`,
});

const highlightTestimonialsFlow = ai.defineFlow(
  {
    name: 'highlightTestimonialsFlow',
    inputSchema: HighlightTestimonialsInputSchema,
    outputSchema: HighlightTestimonialsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
