// This is an autogenerated file from Firebase Studio.
"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckSquare, Goal, Waves } from "lucide-react";
import { CustomVideoPlayer } from "./custom-video-player";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const features = [
  {
    icon: <Waves className="h-8 w-8 text-primary" />,
    title: "Marcações Automáticas de Suporte e Resistência",
    description: "Chega de traçar linhas erradas. O indicador faz todo o trabalho pesado, identificando as zonas de maior probabilidade de reversão com precisão cirúrgrica."
  },
  {
    icon: <CheckSquare className="h-8 w-8 text-primary" />,
    title: (
      <>
        Sinal de Alerta
        <br />
        (Pré-Sinal)
      </>
    ),
    description: "Nunca mais perca uma oportunidade. Um alerta sonoro e visual te avisa ANTES da entrada se formar, para que você tenha tempo de se preparar sem pressa."
  },
  {
    icon: <Goal className="h-8 w-8 text-primary" />,
    title: "Sinal de Confirmação de Entrada",
    description: "O fim da hesitação! Uma seta clara e inequívoca (Verde para CALL, Vermelha para PUT) mostra o MOMENTO EXATO para você abrir a negociação. É só ver o sinal e clicar!"
  }
];

export function SolutionSection() {
  const [videoFinished, setVideoFinished] = useState(false);

  return (
    <section id="solution" className="py-12 lg:py-24 bg-background">
      <div className="container mx-auto px-4">
        <div className="text-center max-w-3xl mx-auto">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold font-headline mb-4">Apresentamos o Indicador ESTRATEGIA CHINESA</h2>
          <p className="text-lg text-muted-foreground mb-8">
            Uma ferramenta inteligente que combina a análise clássica de Suporte e Resistência com um algoritmo exclusivo de confirmação. Ele foi projetado para ser seu maior aliado no gráfico de M1, funcionando com precisão tanto no mercado aberto quanto no OTC.
          </p>
        </div>

        <div className="max-w-3xl mx-auto my-12">
          <Card className="overflow-hidden shadow-lg bg-foreground">
             {!videoFinished ? (
                <CustomVideoPlayer onVideoEnd={() => setVideoFinished(true)} />
             ) : (
                <div className="aspect-video w-full flex flex-col items-center justify-center bg-black bg-opacity-80 p-8 text-center">
                    <h3 className="text-2xl md:text-3xl font-bold font-headline text-white mb-4">Pronto para transformar seu jeito de operar?</h3>
                    <p className="text-lg text-primary-foreground/80 mb-8">Clique no botão abaixo para garantir seu acesso imediato.</p>
                    <Button asChild size="lg" className="w-full max-w-md font-headline text-lg sm:text-xl animate-pulse shadow-lg">
                        <a href="https://pay.kiwify.com.br/N2HRXHr">
                            🔥 SIM, QUERO ACESSO IMEDIATO! 🔥
                        </a>
                    </Button>
                </div>
             )}
          </Card>
        </div>
        
        <div className="text-center mb-12">
           <h3 className="text-2xl lg:text-3xl font-bold font-headline">Veja como a Estratégia Chinesa Simplifica seu Trading:</h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
          {features.map((feature, index) => (
            <Card key={index}>
              <CardHeader className="flex flex-col sm:flex-row items-center gap-4 text-center sm:text-left">
                {feature.icon}
                <CardTitle className="font-headline text-xl">{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
